version: "3.7"
services:
  management-nginx:
    build:
      context: management/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./management:/app
    depends_on:
      - management-php-fpm
    ports:
      - "8080:80"
  management-php-fpm:
    build:
      context: management/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./management:/app
  management-php-cli:
    build:
      context: management/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./management:/app
  management-node-watch:
    image: node:12.7-alpine
    volumes:
      - ./management:/app
    working_dir: /app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  management-node:
    image: node:12.7-alpine
    volumes:
      - ./management:/app
    working_dir: /app
  management-postgres:
    image: postgres:11.2-alpine
    volumes:
      - management-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: management
    ports:
      - "54321:5432"
  management-redis:
    image: redis:5.0-alpine
    volumes:
      - management-redis:/data
    command:
      - 'redis-server'
      - '--requirepass secret'
  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"

volumes:
  management-postgres:
  management-redis: