version: "3.7"
services:
  management-nginx:
    build:
      context: management/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./management:/app
    depends_on:
      - management-php-fpm
    ports:
      - "8080:80"
  management-php-fpm:
    build:
      context: management/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./management:/app
  management-php-cli:
    build:
      context: management/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./management:/app
  management-postgres:
    image: postgres:11.2-alpine
    volumes:
      - management-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: management
    ports:
      - "54321:5432"
  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"

volumes:
  management-postgres: